/*
 * File: pa4Globals.c
 * Description: Global variables for pa4.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include "pa4.h"
#include "pa4Strings.h"

// Used in hash()
int HashPrime = HASH_PRIME;
int HashStartVal = HASH_START_VAL;

